import Layout from "@/components/Layout";
import Image from "next/image";
import Head from "next/head";
import profilePic from "../../public/images/profile/diegoFoto.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Diego Rojas</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light 2xl:">
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className="flex items-center text-dark justify-between w-full lg:flex-col">
            <div className="w-1/2 flex justify-end md:w-full md:justify-center sm:justify-center">
              <Image
                src={profilePic}
                alt="ImageProfile"
                className="w-[90%] h-auto md:inline-block md:w-[80%]"
                priority
                sizes="fill"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center dark:text-light lg:w-full lg:text-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects, showcasing my expertise in React.js and
                web development.
              </p>
              <div className=" flex items-center self-start mt-2 lg:self-center">
                <Link
                  href={"/Resume_Diego.pdf"}
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:text-dark hover:bg-light border border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark dark:hover:bg-transparent dark:hover:border-light dark:hover:text-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"}></LinkArrow>
                </Link>
                <Link href={"mailto:diegoarojas@hotmail.es"} target={"_blank"} className="m-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base">
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
        <div className="absolute right-8 -bottom-8 inline-block  w-24 md:hidden">
          <Image src={lightBulb} alt="Diego" className="w-full h-auto" priority/>
        </div>
      </main>
    </>
  );
}
